[package]
name = "lang"
version = "0.1.0"
edition = "2021"

[[bin]]
doc = false
name = "lang"

[build-dependencies]
cfgrammar = "0.13"
lrlex = "0.13"
lrpar = "0.13"
once_cell = "1.18.0"

[dependencies]
cfgrammar = "0.13"
lrlex = "0.13"
lrpar = "0.13"
once_cell = "1.18.0"
